version: "3.9"

services:
  db:
    image: postgres
    
    environment:
      - POSTGRES_DB=social_media_db
      - POSTGRES_USER=sagar
      - POSTGRES_PASSWORD=h841207s

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db